export default [
  "<i>I wonder what he was doing in the garden yesterday..</i>",
  "Hayashi-kun is beside me, staring off into the distance. Not listening to the teacher, nor writing down notes.. What is he even doing at this school?",
  "How strange.",
  "“What page were we on again Hayashi?” a sudden question. The subject teacher caught on, this guy wasn’t paying attention.",
  "“It was page 101.”",
  "I shot a glance at him in surprise, he actually guessed the page…",
  "Even the teacher was caught off guard, immediately trailing back to the discussion. As you would’ve expected, my seatmate... returned to his own world.",
  "Is he really listening in class but it seems like he isn’t..?",
  "Or is he truly just… here to burn time?",
  "“You’ve been staring at me.” he mentioned.",
  "“...” I stared, my brows furrowed. “I wasn’t.”",
  "“Ah, is that so? How convincing.” he sarcastically replied.",
  "Just when I thought I found someone nice, he’s actually just a sarcastic bastard.",
  "“I just thought you were weird, that’s all there is to it.” I scoffed.",
  "“Am I any weirder than someone who stares for no reason?”",
  "There I shut my mouth… and really wanted to shut his.",
  "Our subject teacher noticed this exchange, and glared daggers at the both of us. Although our classmates noticed too, they simply brushed it off as the two weirdos acting strange.",
  "This time I glared at him, and he felt it.",
  "He glanced in my direction and…",
  "Just went back to staring off into the distance.",
  "For the rest of the class… I criticized myself for having such a strange exchange with someone I barely know.",
  "<i>What was I even doing to glare at him like that?</i>",
  "Soon the bells chimed and I walked around the campus, disregarding my empty stomach, disregarding everything else.",
  "The sky is nice today too… the flowers in the garden are ever blooming.",
  "No one’s bothering me today as well…",
  "None at all... nothing..",
  "Still... no matter how much I distract myself..",
  "I’m going crazy over that letter.",
  "Normally, I would’ve tossed that letter to the trash without a second thought—but I couldn’t…",
  "Now I’m stuck, frustratingly curious as to what those previous letters contained…",
  "This feeling of frustration.. I must’ve redirected it to Hayashi-kun earlier.",
  "Well, <i>he deserved it.</i>",
  "I already told myself to forget about it last night.",
  "But I guess such things don't leave when you ask nicely."
];
