export default [
  "October has once again welcomed me with open arms, the harsh heat of the sun has begun to dwindle, and we slowly shift to another season.",
  "While the seasons continue to change, the class remains frozen, forever failing to open up my cold heart. I’ve longed for true friendship… but it can’t manifest here. As much as I’ve been pestered in this academy, there is one thing that has never left my mind.",
  "Last month, I feared for my well-being. I assumed there was a stalker sneaking letters in the seams of my stuff. My thoughts rambled and came to the conclusion that if someone had something to tell me, and was capable enough to sneak these letters in my bag, they better talk to me upfront. Thus I never bothered to open them, they ended up not being read, but straight for the bins.",
  "“Take out your books and answer page 76, I’ll give you half an hour to do so. That’s more than enough time so no excuses.” the teacher announced followed by the tired yawns of the students.",
  "“Sensei, can’t you extend by 10 minutes?” one asked.",
  "“We still have too many to discuss and your tests are nearing so I can’t extend any further.”",
  "Whilst they complained and some just did as told, I opened the book to said page, and what awaited me was not questions, but a letter somehow snuck in once again.",
  "<i>Just who is it that managed to put a letter exactly at this page?</i>",
  "<i>How creepy.</i>",
  "So far this is the third letter… I stared at it for a moment longer.",
  "<i>Seeing as it’s merely a piece of paper, there shouldn’t be any harm in opening them… right?</i>",
  "If the contents somehow disgust me, I surely have enough tolerance for it..",
  "Then... almost as though it was Pandora's box.. I ripped the letter open and scanned its contents.",
  "<hr class='separator' />",
  "<i>Mizuki, my dearest.</i>",
  "<i>This is the fourth letter that I’ve written.</i>",
  "<i>Don’t fret if the numbers don’t match as I’m unsure if you have read the past letters nor have you come to believe the words I’ve said.</i>",
  "<i>But if this somehow reaches you, do believe that I see no other than you to be the one.</i>",
  "<i>From what we’ve gone through the future, I assure you that the journey we’ll go through is that of beauty and fulfillment.</i>",
  "<i>I’ve already begun this journey with you, I hope for nothing but to end this journey with you as well.</i>",
  "<i>-your future lover.</i>",
  "<hr class='separator' />",
  "The contents seemed to spout ridiculous claims that counter any sense of realism, this nonsense of being from the future...",
  "<i>I don’t think anybody in this school nor anybody from middle school has developed some sort of interest in me, so what is this?</i>",
  "Just from the first paragraph, it appears this future lover of mine has sent four letters. I’ve already thrown away two letters, and read this third that I’ve come across. The numbers do indeed not match.",
  "I shall throw this one out too… <i>But…</i> I feel like I can’t.",
  "<i>This is ridiculous…</i>",
  "While I began to question myself, I grew unaware of the ticking time... and soon enough, the teacher tapped the board informing us of the remaining five minutes.",
  "I swiftly stuffed the letter in my bag and was greeted with several unanswered essays.",
  "<i>Perhaps this is the consequence of reading that creepy letter… I knew something was bound to happen from opening that embodiment of Pandora’s box…</i>",
  "Glancing to my right, there sat Hayashi-kun, his pen swaying left and right.. dancing it seemed. “Perhaps it’s better if you glanced at your own paper and actually answered?” he spoke.",
  "“Oh.. right.” I replied... this is the first time we’ve spoken.",
  "“What have you been doing for the past 26 minutes to have a page so clean?”",
  "“I… <i>ugh…</i> mind your own business.”",
  "“It should be me saying that, just focus on your paper and answer quickly, you can do it if you rush.”",
  "It intrigued yet annoyed me by how casual he’s acting. My eyes once again landed on his page and it was filled to the brim with answers. While mine sat.. collecting dust instead of answers.",
  "<i>How annoying…</i>"
];
