export default [
  "Classes came to an abrupt end, I who was tasked with class duty watched as my classmates joyfully left the confines of the room. Their conversations of where they wished to hang out poked fun at me who had the mop and broom seemingly forcing themselves onto me, making me clean the room despite my lack of interest and will.",
  "For a regular student, the idea of cleaning the classroom by yourself when you have other classmates on duty as well is tiring and not preferred. But it striked me just right, from the start I’ve been a loner in class.",
  "I’ve never meddled with anyone in class, nor have anyone interacted with me. I’ve long cemented myself since my speech at the entrance ceremony that I simply wish to go through my senior year without interacting with anybody.",
  "That however was deterred by my seatmate Hayashi-kun from Japanese class earlier. I distracted him from his work so a short exchange of words was alright. But the problem comes with…",
  "“Hey, Aihara-san right?” a bunch of girls surrounded me.",
  "“Hm?”",
  "“A few guys from the neighboring schools saw you in a group photo of us as a class, and they were eager to get to know you!”",
  "“Can’t you tell them that I’m not interested?” I scratched my cheek.",
  "“That’s no fun! Just an hour with them since we’re also missing one person!” they pleaded with me.",
  "“No.. I’m not interested. I’m preoccupied.”",
  "Like a switch, their interested and vibrant expressions turned sour.",
  "But I didn't mind, this is just how I am. So I continued to sweep as they left the classroom one by one. Acting like I couldn’t hear them badmouthing me.",
  "“<i>Tch…</i> I told you she’s a loner.” I heard their faint conversation along the hallway continue.",
  "Evident from what just happened, <b>I’m not good with people.</b> For too long I have kept on carrying myself as someone who doesn’t interact with others.",
  "I prefer talking to myself like this rather than experiencing the- “I’m on duty as well!” a guy with blonde hair shouted as he barged through the door. “Sorry Aihara-san! I was just taking care of something!” he smiled.",
  "Normally I’d be annoyed by his ignorance of duty and not informing me beforehand. But I had no time for this, I just wanted to get it over with. “Just go ahead and clean the board then help me with the dust.”",
  "He quickly got to work and I tried to finish this duty as soon as possible. “My name’s Sakuragi Ren, you can call me Ren.”",
  "“...”",
  "“Hey, can I ask you something?”",
  "I didn’t bother to reply and simply looked at him, letting him proceed.",
  "“You’re pretty cute, how come you never talk to others in class? You’re always looking off into the distance, eating by yourself, you’re always alone you know?”",
  "“I have my reasons.” I said, continuing to sweep the floor, but he never took his eyes off me. “It’s merely how I prefer to live my life, there’s no problem with it.”",
  "“It’s such a waste though, I’m friends with the owner of a nearby cafe, wanna come with me?” he said.",
  "“Are we really on terms to hangout?” I sighed. “I’m done with cleaning, you came in late and I was already done with half so you finish the rest.”",
  "“Okay, just know that I’m not giving up a cutie like you so easily.”",
  "I had already grabbed my bag and quickly made my way down the hallway after slamming the door shut, pushing myself away from him who was crawling his way to my nerves with all that sweet talk.",
  "By the time I got out, the sun had already radiated its golden aura as it began to set. Now, the buildings had become eerily quiet, empty of students, and my footsteps rang louder than ever.",
  "Before I ventured back to the dormitory, I had to cool off so straight to the garden I headed. I set down my bag and took a peek at the letter for any hidden messages, but there were none. The content remained the same, there was no evidence it came from the future. None except its persistent nature of somehow appearing in my belongings.",
  "If this is the fourth letter, I made a grave mistake of throwing the other two. The writer said it himself though, he’s unsure of whether the letters would make its way to me. So it shouldn't be my fault that I’ve only touched three out of the four.",
  "Setting these letters aside, Sakuragi seemed way too interested in me, at least that’s what I think… giving me strange nicknames. I have no way of deducing if that’s just how he is or if he’s really interested in me. He even went out of his way to do his duties just to talk to me.",
  "Then again… the letters. The handwriting seemed too consistent, one could assume it’s a font. Yet it carries features that resemble that of human handwriting.",
  "Surely I’m not being pranked or anything?",
  "While I doted on myself and stared off into the distance, I found Hayashi Kousei; my seatmate earlier. I’m not entirely familiar with him but he’s different, his voice was steady, like a metronome clicking in the background. Despite my lack of connection, I know his name because I hear others complaining about him, he’s so annoying they say, his personality being unbearable and such.",
  "Just from glancing at his direction, he could immediately tell as I found myself having eye contact with him who stood before the tulip section. I quickly averted my gaze and worried as I caught the attention of another classmate, I wasn’t in the mood for conversing…",
  "…but I waited.",
  "Perhaps I should just leave and avoid the trouble… but, as I got buried in my thoughts, I was late to notice that he never left his spot.",
  "There he remained still, going back to minding his own business after that accidental eye contact.",
  "How unusual… it would’ve been better if everyone in class was tolerable like him. Interactive but never forceful… unlike that guy earlier.",
  "In my chase for the garden to clarify my thoughts… it seemed as though I only pushed myself further to get lost in them. I was wasting time thinking about him and the letters, then quickly noticed the departure of the golden sun. The moon had taken its turn, and it was also the dormitory’s turn for me to occupy.",
  "No matter how much I wanted to stay and observe this strange seatmate of mine, I left the area to get my much needed rest."
];
